package com.kramerica.meatworldavatar;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HABIT.
 */
public class Habit {

    private Long id;
    private long avatarId;
    private Integer hour;
    private Integer weekday;
    private Integer month;
    private Integer dayOfMonth;
    private Integer dayOfYear;

    public Habit() {
    }

    public Habit(Long id) {
        this.id = id;
    }

    public Habit(Long id, long avatarId, Integer hour, Integer weekday, Integer month, Integer dayOfMonth, Integer dayOfYear) {
        this.id = id;
        this.avatarId = avatarId;
        this.hour = hour;
        this.weekday = weekday;
        this.month = month;
        this.dayOfMonth = dayOfMonth;
        this.dayOfYear = dayOfYear;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getAvatarId() {
        return avatarId;
    }

    public void setAvatarId(long avatarId) {
        this.avatarId = avatarId;
    }

    public Integer getHour() {
        return hour;
    }

    public void setHour(Integer hour) {
        this.hour = hour;
    }

    public Integer getWeekday() {
        return weekday;
    }

    public void setWeekday(Integer weekday) {
        this.weekday = weekday;
    }

    public Integer getMonth() {
        return month;
    }

    public void setMonth(Integer month) {
        this.month = month;
    }

    public Integer getDayOfMonth() {
        return dayOfMonth;
    }

    public void setDayOfMonth(Integer dayOfMonth) {
        this.dayOfMonth = dayOfMonth;
    }

    public Integer getDayOfYear() {
        return dayOfYear;
    }

    public void setDayOfYear(Integer dayOfYear) {
        this.dayOfYear = dayOfYear;
    }

}
