package com.kramerica.meatworldavatar;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ACCELERATION.
 */
public class Acceleration {

    private Long id;
    private java.util.Date timestamp;
    private Float x;
    private Float y;
    private Float z;
    private Long eventId;

    public Acceleration() {
    }

    public Acceleration(Long id) {
        this.id = id;
    }

    public Acceleration(Long id, java.util.Date timestamp, Float x, Float y, Float z, Long eventId) {
        this.id = id;
        this.timestamp = timestamp;
        this.x = x;
        this.y = y;
        this.z = z;
        this.eventId = eventId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(java.util.Date timestamp) {
        this.timestamp = timestamp;
    }

    public Float getX() {
        return x;
    }

    public void setX(Float x) {
        this.x = x;
    }

    public Float getY() {
        return y;
    }

    public void setY(Float y) {
        this.y = y;
    }

    public Float getZ() {
        return z;
    }

    public void setZ(Float z) {
        this.z = z;
    }

    public Long getEventId() {
        return eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

}
