package com.kramerica.meatworldavatar;

import java.util.List;
import com.kramerica.meatworldavatar.meatdomain.DaoSession;
import de.greenrobot.dao.DaoException;

import com.kramerica.meatworldavatar.meatdomain.AccelerationDao;
import com.kramerica.meatworldavatar.meatdomain.EventDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EVENT.
 */
public class Event {

    private Long id;
    private Long avatarId;
    private java.util.Date time;
    private Integer sensor_type;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient EventDao myDao;

    private List<Acceleration> accelerationList;

    public Event() {
    }

    public Event(Long id) {
        this.id = id;
    }

    public Event(Long id, Long avatarId, java.util.Date time, Integer sensor_type) {
        this.id = id;
        this.avatarId = avatarId;
        this.time = time;
        this.sensor_type = sensor_type;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getEventDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAvatarId() {
        return avatarId;
    }

    public void setAvatarId(Long avatarId) {
        this.avatarId = avatarId;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public Integer getSensor_type() {
        return sensor_type;
    }

    public void setSensor_type(Integer sensor_type) {
        this.sensor_type = sensor_type;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Acceleration> getAccelerationList() {
        if (accelerationList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            AccelerationDao targetDao = daoSession.getAccelerationDao();
            List<Acceleration> accelerationListNew = targetDao._queryEvent_AccelerationList(id);
            synchronized (this) {
                if(accelerationList == null) {
                    accelerationList = accelerationListNew;
                }
            }
        }
        return accelerationList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetAccelerationList() {
        accelerationList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
